language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

#Travis CI server home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY  # Travis repo settings에서 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에서 설정된 값
    bucket: freelec-springboot-build-kbc # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근은 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait_until_deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY  # Travis repo settings에서 설정된 값
    secret_access_key: $AWS_SECRET_KEY  # Travis repo settings에서 설정된 값
    bucket: freelec-springboot-build-kbc # s3 버킷
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행완료시 메일로 알람전송
notifications:
  email:
    recipients:
      - bckang92@naver.com
